baseURL: https://emily5.com
title: Emily M Gomez
defaultContentLanguage: 'en'
googleAnalytics: ''

params:
  image: /images/banner.png
  subtitle: Hi, my name is Emily. I have a background in software engineering and aspire to be a graphic designer. The purpose of this site is to showcase my work.
  #copyright: All rights reserved.
  author: Emily Gomez
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        art: 4
        archive: 6
        design: 2
        default: 3
      mobile:
        default: 2
        archive: 3
        design: 1
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:emgnomez@gmail.com'
      landing: true
    - icon: 'fab fa-github fa-lg'
      url: 'https://github.com/emgnomez/mywebsite'
      landing: true
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/emgnomez'
    - icon: 'fab fa-linkedin-in fa-lg'
      url: 'https://linkedin.com/in/em-gomez'
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: work
      url: /work/
      weight: 1
    - name: design
      url: /tags/design/
      weight: 2
    - name: art
      url: /tags/art/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
    - name: about
      url: /about/
      weight: 5
